import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import { BiArrowBack } from 'react-icons/bi'

export default function Home() {
  const files = [
    {"id":1,
      "filename":"name1",
      "size":"20 GB"
    },
    {"id":2,
      "filename":"name2",
      "size":"20 GB"
    },
    {"id":3,
      "filename":"name3",
      "size":"20 GB"
    }
  ]

  return (
    <>
      <Head>
        <title>Google File ✨</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.container}>
          <section className={styles.trashNav}>
            <div className={styles.trashNav_count}>
              <BiArrowBack className={styles.backBtn} />
              <div>
                <p>3 selected</p>
                <p>2 GB</p>
              </div>
            </div>
            <button className={styles.deleteBtn}>Delete</button>
          </section>
          <section className={styles.allSelect}>All Select
            <input style={{ scale: '1.5', Accentcolor: 'green' }} type="checkbox" ></input>
          </section>
          <ul>
            {files.map( (f) => (
              <Card f={f} key={f.id} />
            ))}         
          </ul>
        </div>

      </main>
    </>
  )

  function Card({f}) {
    const [isSelect, setisSelect] = useState(false);

    function handleSelect(e) {
      if (e.target.checked === true) {
        setisSelect( prev => !prev)
      }
      else {
        setisSelect(prev => !prev)
      }
    }

    return (
      <label className={styles.cardContainer}>
        <li style={isSelect ? { backgroundColor: 'rgb(26 114 230)' } : {}} className={styles.card} >
          <div className={styles.cardLeft}>
            <div className={styles.photo}>file {f.id}</div>
            <div className={styles.fileInfo}>
              <div>File: file {f.filename}</div>
              <div>Size: {f.size}</div>
            </div>
          </div>
          <input style={{ scale: '1.5', Accentcolor: 'green' }} onChange={handleSelect} type="checkbox" value={f.id}></input>
        </li>
      </label>
    );
  }
}