import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import { BiArrowBack } from 'react-icons/bi'
import { IoMdClose } from 'react-icons/io'
import Card from '../component/Card';
import { setConstantValue } from 'typescript';
import { once } from 'events';
// import audio from '/public/click.wav'
import useSound from 'use-sound';
import boopSfx from '/public/click.mp3'
import checkSound from '/public/enable-sound.mp3'
import uncheckSound from '/public/disable-sound.mp3'
function Selectbar(props) {

  const [play] = useSound(boopSfx);
  return (
    <>
      {/* <audio controls src="/public/click.wav" /> */}
      <div className={styles.trashNav_count}>
        {
          /* <BiArrowBack className={styles.backBtn} /> */
        }
        <IoMdClose onClick={(e) => { props.setselectedId([]); props.playOff() }} className={styles.backBtn} />
        <div>
          <p>{props.length} selected</p>
          <p>{props.total} GB</p>
        </div>
      </div>
      <button onClick={play} className={styles.deleteBtn}>Delete</button>
    </>
  );
}
function Backbar(props) {
  return (<div className={styles.trashNav_count}>
    {
      /* <BiArrowBack className={styles.backBtn} /> */
    }
    <BiArrowBack className={styles.backBtn} />
    <div>
      <p>Trash</p>
    </div>
  </div>);
}
export default function Home() {
  const files = [
    {
      "id": 1,
      "filename": "name1",
      "size": "5 GB"
    },
    {
      "id": 2,
      "filename": "name2",
      "size": "1 GB"
    },
    {
      "id": 3,
      "filename": "name3",
      "size": "20 GB"
    }
  ];
  const [selectedId, setselectedId] = useState([]);
  const [isChecked, setisChecked] = useState(false);
  const [total, settotal] = useState('');

  useEffect(() => {
    //     if (isChecked) {
    //       () => {
    //         useSound(checkSound,
    //           { volume: 0.11 })
    // }
    //     }
    //     else {
    //       () => {
    //       useSound(uncheckSound,
    //         { volume: 0.11 })
    //       }
    //     }
    console.log(isChecked)
    // setisChecked(false)
    // const total = files.filter(file => file.id == selectedId)
    // console.log(selectedId)
    const totalArray = []
    let total
    // for (let i = 0; i < selectedId.length; i++) {
    // const id =selectedId.map(s => {
    //   total = files.filter(file => file.id == s)
    // })
    for (let i = 0; i < selectedId.length; i++) {
      total = files.filter(f => f.id === selectedId[i])
      totalArray.push(total[0])
    }
    const t2 = totalArray.map(t => parseInt(t.size)).reduce((prev, current) => prev + current, 0)
    settotal(t2)
    // }
    // totalArray.push(total)
    // totalArray.push(total)
    // total.map(t => {
    //   console.log(t.id)
    // })
    // console.log(Array.isArray(total))
    if (selectedId.length >= 1) {
      setisChecked(true)
    } else {
      setisChecked(false)
    }
  }, [selectedId, isChecked]);

  function allSelect() {
    const items = []
    setisChecked(prev => !prev)
    // if (isChecked) {
    for (let i = 0; i < files.length; i++) {
      const id = files[i].id
      items.push(id)
    }
    setselectedId(items)
    // }
    if (isChecked === true) {
      setselectedId([])
    }
  }
  const visible = selectedId.length >= 1

  const [playOn] = useSound(checkSound,
    { volume: 0.11 })
  const [playOff] = useSound(uncheckSound,
    { volume: 0.11 })
  return (
    <>
      <Head>
        <title>Google File ✨</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div style={{ position: 'sticky', top: '0', zIndex: '2000' }}>
            <section
              // onAnimationEnd={(e)=>{}}
              className={[styles.SelectNav, !visible ? styles.fadeOut : styles.fadeIn].join(" ")}>
              <Selectbar playOff={playOff} setisChecked={setisChecked} total={total} length={selectedId.length} setselectedId={setselectedId} selectedId={selectedId} />
            </section>


            <section
              className={[styles.trashNav, visible ? styles.fadeOut : styles.fadeIn].join(" ")}>
              <Backbar />
            </section>

            <label onMouseUp={() => !isChecked ? playOn() : playOff()} for="checkbox_id" className={styles.allSelect} >
              All Select
              <input id="checkbox_id" onChange={allSelect} checked={isChecked} style={{ Accentcolor: 'green' }} type="checkbox" ></input>
            </label>
          </div>
          <ul>
            {files.map((f) => (
              <Card playOn={playOn} playOff={playOff} setisChecked={setisChecked} files={files} f={f} key={f.id} setselectedId={setselectedId} selectedId={selectedId} />
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}